spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC
    username: root
    password: mybatis$
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: mysql

---
spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
      name: ${job.name:NONE}